<?php

namespace common\controllers;

use common\models\Decrypt;
use common\services\CConstant;
use common\util\Common;
use common\util\Request;
use Yii;
use yii\base\UserException;
use yii\filters\ContentNegotiator;
use yii\filters\Cors;
use yii\web\Controller;
use common\Constants;
use common\BizResult;
use yii\helpers\ArrayHelper;
use common\models\ValidModel;
use yii\web\Response;
use common\logic\sysuser\UserLogic;

class BaseController extends Controller
{

    public $enableCsrfValidation = false;

    public function init()
    {
        Yii::info(Request::input(), 'requestInfo');
        if (Yii::$app->getRequest()->isOptions) {
            exit;
        }

        parent::init();
    }

    /**
     * @return array
     */

//    public function behaviors()
//    {
//        $behaviors =  parent::behaviors(); // TODO: Change the autogenerated stub
//        unset($behaviors['authenticator']);
//
//        $behaviors['corsFilter'] = [
//            'class'=>Cors::className(),
//            'cors'=>[
//                'Origin' => ['*'],
//                'Access-Control-Request-Method'=>['*'],
//                'Access-Control-Request-Headers'=>['*'],
//                'Access-Control-Allow-Credentials'=>true,
//                'Access-Control-Max-Age'=>3600,
//                'Access-Control-Expose-Headers'=>['X-Pagination-Current-Page'],
//            ],
//        ];
//
//        /*$behaviors['contentNegotiator'] = [
//            'class'=>ContentNegotiator::className(),
//            'formats'=>[
//                'application/json'=>Response::FORMAT_JSON
//            ]
//        ];*/
//        return $behaviors;
//    }

    /**
     * 开启事务
     *
     * @return \yii\db\Transaction
     * @throws \yii\db\Exception
     */

    public function beginTransaction()
    {
        $trans = Yii::$app->db->beginTransaction();
        //\Yii::$app->getDb()->createCommand("SET drds_transaction_policy = 'XA'")->execute();
        return $trans;
    }

    /**
     * getPostParam --获取post参数，为空时返回默认值
     * @author JerryZhang (zhanghongdong@360.net)
     * @param null $name
     * @param null $default
     * @return array|mixed
     * @cache No
     */
    protected function getPostParam($name = null, $default = null)
    {
        $request = Yii::$app->request;
        return $request->post($name, $default);
    }

    /**
     * getParam --获取参数，为空时返回默认值
     * @author JerryZhang (zhanghongdong@360.net)
     * @param null $name
     * @param null $default
     * @param string $method
     * @return array|mixed
     * @cache No
     */
    protected function getParam($name = null, $default = null, $method = 'get')
    {
        $request = Yii::$app->request;
        $method = strtolower($method);
        if ($method == 'post') {
            return $request->post($name, $default);
        } else {
            return $request->get($name, $default);
        }
    }

    /**
     * getRequestParam --获取参数，为空时返回默认值
     * @author JerryZhang (zhanghongdong@360.net)
     * @param null $name
     * @param null $default
     * @return array|mixed
     * @cache No
     */
    protected function getRequestParam($name = null, $default = null)
    {
        $request = Yii::$app->request;
        if ($name === null) {
            return ArrayHelper::merge($request->get(), $request->post());
        } else {
            return $request->post($name, $request->get($name, $default));
        }
    }

    public function renderJson($data)
    {
        $rt = [
            'code' => 0,
            'message' => 'success',
            'data' => []
        ];

        if ($data instanceof \Exception) {
            $rt['code'] = $data->getCode() === 0 ? Constants::WEB_ERROR_PARAM : $data->getCode();
            $rt['message'] = $data->getMessage();
        } else {
            $rt['data'] = $data;
        }
        $log['request_url'] = Yii::$app->request->pathInfo;
        $log['request_params'] = Request::input();
        $log['response'] = $rt;
        Yii::info(json_encode($log, JSON_UNESCAPED_UNICODE), 'process');
        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = $rt;
        return $response;
    }

    protected function generateCommFilters(array &$filters)
    {
        return $filters;//extends this function to gen the common filters at every request
    }

    public function getParamWithRange($key, array $range, $default = null)
    {
        $value = $this->getParam($key, $default);
        return in_array($value, $range) ? $value : $default;
    }

    public function getParamWithIntRange($key, $min = 0, $max = 100, $default = 0)
    {
        $value = $this->getParam($key, $default);
        $value = intval($value);
        return $value >= $min && $value <= $max ? $value : $default;
    }

    protected function verifyParam($defaultScenarios, $post, $rules, $is_throw_exception = true, $formName = "")
    {
        $check = new ValidModel();
        $check->setDefaultScenarios($defaultScenarios);
        $check->setRules($rules);
        $check->load($post, $formName);

        $res = $check->validate();

        if ($is_throw_exception && !$res) {
            foreach ($check->getErrors() as $key => $value) {
                BizResult::ensureNotFalseMsg(false, $value[0]);
            }
            BizResult::ensureNotFalse($res, Constants::WEB_ERROR_PARAM);
        }
        return $res;
    }

    /**
     *get request
     *
     * @return \yii\console\Request|\yii\web\Request
     */

    public function getRequest()
    {
        return \Yii::$app->getRequest();
    }

    /**
     * get session Object
     *
     * @return mixed|\yii\web\Session
     */

    public function getSession()
    {
        return \Yii::$app->session;
    }

    /**
     * get redis
     *
     * @return object
     */
    public function getRedis()
    {
        return \Yii::$app->redis;
    }

    /**
     * @params array $data
     * @return mixed
     */
    public function keyMod($data)
    {
        if (!$data || !is_array($data)) {
            return $data;
        }
        foreach ($data as $key => $item) {
            if (is_string($key)) {
                $newKey = str_replace('_', ' ', strtolower($key));
                $newKey = lcfirst(str_replace(' ', '', ucwords($newKey)));
                unset($data[$key]);
                $data[$newKey] = $this->keyMod($item);
            } else {
                $data[$key] = $this->keyMod($item);
            }
        }
        return $data;
    }

    /**
     * 参数key转为小写+下划线
     *
     * @return void
     */
    protected function key2lower($data)
    {
        if (!$data || !is_array($data)) {
            return $data;
        }
        foreach ($data as $_k => $_v) {
            $_key = preg_replace_callback('/([A-Z]+)/', function ($matchs) {
                return '_' . strtolower($matchs[0]);
            }, $_k);
            if ($_key != $_k) {
                $data[$_key] = $_v;
                unset($data[$_k]);
            }
        }
        return $data;
    }

    /**
     * 获取当前毫秒时间戳
     *
     * @return number
     */
    public function getMicroTime()
    {
        list($msec, $sec) = explode(' ', microtime());
        $msectime = (float)sprintf('%.0f', (floatval($msec) + floatval($sec)) * 1000);
        return $msectime;
    }

    /**
     * 防止刷新
     * @param $_this object 控制器某个方法内的$this
     * @param $seconds int 防止刷新间隔时间（单位秒，默认1S）
     * @param $sign string 请求身份标识符
     * @param $route string 访问路径字符串
     * @return bool true可以访问/false不可以访问
     */
    public function preventRefresh($_this="", $seconds=1, $sign="", $route=""){
        if(!empty($_this)){
            $route = "";
            $route.= isset($_this->module->id) ? $_this->module->id : "";
            $route.= isset($_this->id) ? $_this->id : "";
            $route.= isset($_this->action->id) ? $_this->action->id : "";
            if(empty($route)){
                return true;
            }
            $header = \Yii::$app->request->headers->toArray();
            if(!isset($header['authorization'][0])){
                return true;
            }else{
                $sign = trim($header['authorization'][0]);
            }
            if(empty($sign)){
                return true;
            }
            $sign = md5($sign);
        }
        if(empty($sign) || empty($route)){
            return true;
        }
        $redis = \Yii::$app->redis;
        $k="PR_".$sign."_".$route;
        $rs = $redis->keys($k);
        if(!empty($rs)){
            return false;
        }else{
            $redis->set($k,"1");
            $redis->expire($k, $seconds);
            return true;
        }
    }

}
